PRAGMA foreign_keys = ON;

ALTER TABLE documents ADD COLUMN file_name TEXT NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN file_size INTEGER NOT NULL DEFAULT 0;
ALTER TABLE documents ADD COLUMN file_type TEXT NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN file_text TEXT NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN uploaded_at TEXT NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN ai_status TEXT NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN ai_analysis TEXT NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN ai_model TEXT NOT NULL DEFAULT '';
ALTER TABLE documents ADD COLUMN ai_analyzed_at TEXT NOT NULL DEFAULT '';
